Creating an example for an app with backend component
grafana/grafana-plugin-examples pull request #118
Opened 2022-11-28 18:32 UTC by tab0r

The [plugin-tools](https://github.com/grafana/plugin-tools) command `yarn create @grafana/plugin` allows creation of an app with backend, but we don't have an example for it yet. Since it's what I need for a current project, I thought I'd share what I came up with.

2022-11-28 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana-plugin-examples?pullRequest=118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana-plugin-examples?pullRequest=118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana-plugin-examples?pullRequest=118) it.</sub>

2022-11-28 18:38 UTC, tab0r commented
Creating this as a draft, since there are a few things I'd like to do/know:

- [ ] do we really want all the build files included in the apps?
- [ ] add something in the UI to display the button responses
- [ ] add something to hit the `/echo` route
- [ ] update docs
- [ ] add some integration tests
- [ ] add unit tests

2023-01-11 12:46 UTC, mckn reviewed
This is great, thanks for your contribution! 

To make this even better we should probably do the following:

- Replace some of the pages with one or two pages that show case this example a bit more by calling the app backend and displaying the response.
- Add some e2e tests that verifies that the page that calls the app backend works as expected.

By doing the changed mentioned above this example will also verify that we are not breaking any of the APIs being used while working on future versions of Grafana. All of the examples that contains e2e tests will regularly run agains the main branch of Grafana.

2023-01-11 17:33 UTC, tab0r commented
I definitely agree with both points @mckn . I'm not sure how much of that I can get done in the short term, as I'm honestly not sure how much work it entails. But, tomorrow I'll be pairing with a teammate to discuss our implementation plans. There's a chance that taking care of those things will be just want we need to get started on our project. If not, I wouldn't be opposed to closing this and creating an issue for it so that it can be tackled as availability opens up.

2023-01-24 09:33 UTC, mckn commented
> I definitely agree with both points @mckn . I'm not sure how much of that I can get done in the short term, as I'm honestly not sure how much work it entails. But, tomorrow I'll be pairing with a teammate to discuss our implementation plans. There's a chance that taking care of those things will be just want we need to get started on our project. If not, I wouldn't be opposed to closing this and creating an issue for it so that it can be tackled as availability opens up.

Okay, no worries! I can help you with those changes if that feels ok? @wbrowne before I proceed, can you have a look at the BE code?

2023-01-24 10:46 UTC, wbrowne requested changes
Just a couple of small things that should be pretty easily fixed 😄 Thanks for providing this!

2023-01-24 10:46 UTC, wbrowne commented on examples/app-with-backend/src/components/AppConfig/AppConfig.tsx
> +  isApiKeySet: boolean;
Here we can make use of `secureJsonFields KeyValue<boolean>` to achieve this behaviour without the added field. This should exist on the PluginMeta. 

For reference the PR that added support: https://github.com/grafana/grafana/pull/55313

2023-01-25 17:42 UTC, tab0r commented
Thank you @mckn and @wbrowne ! After the team discussion I mentioned we decided to not go down this path at the moment. But now I'm invested! So still keeping an eye on this and will jump back in when I can. :smile:

2023-02-15 13:24 UTC, mckn approved these changes
LGTM!

2023-02-16 11:59 UTC, wbrowne commented on examples/app-with-backend/src/components/AppConfig/AppConfig.tsx
> +  isApiKeySet?: boolean;
This can be removed now I think!

2023-02-16 14:00 UTC, wbrowne approved these changes
LGTM.

Spoke offline and we will move to `secureJsonFields` support once G10 rolls out

2023-02-18 12:11 UTC, tab0r commented
Thank you so much for cleaning this up for me @mckn ! I'll leave the pleasure of pushing the big green button to you, it's only fair. :D

2023-02-20 08:22 UTC, merged