Scenes app example: Add LLM plugin integration demo page
grafana/grafana-plugin-examples pull request #273
Opened 2024-04-11 17:18 UTC by nmarrs

Update the create plugin template scenes app to include a example integrating the LLM plugin

NOTE: I'm not sure how to test this locally, but will work on figuring this out when I am back in next week. In meantime, with LLM plugin configured here are the demos that should be possible with these changes 🦖 Also there is some `package.json` ❤️ needed to get versions updated correctly / update react to 18+ from 17 

As a side note it would be super cool if there was a way to somehow have a single github repo for demos vs needing to duplicate changes between this repo and `plugin-tools` 😬 (i.e. [see this PR with duplicate changes](https://github.com/grafana/plugin-tools/pull/873))

https://github.com/grafana/scenes-app-template/assets/22381771/36b21e2d-aa4c-4515-baea-661c0764058c

https://github.com/grafana/scenes-app-template/assets/22381771/c67bcf88-3e25-4558-9647-02b0929a2ec3

https://github.com/grafana/scenes-app-template/assets/22381771/efe08fd8-fe64-47f9-b2e9-d198b061d610

2024-04-11 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/grafana-plugin-examples?pullRequest=273) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/grafana-plugin-examples?pullRequest=273) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/grafana-plugin-examples?pullRequest=273) it.</sub>

2024-04-11 17:22 UTC, nmarrs commented on examples/app-with-scenes/src/pages/WithDrilldown/WithDrilldown.tsx
> +                title: `${decodeURI(roomName)} overview`,
This change is fixing an issue that was addressed in old dead repo (see [here for context](https://github.com/grafana/scenes-app-template/pull/2))

2024-04-17 09:48 UTC, sympatheticmoose requested changes
Hey @nmarrs thanks again for these contributions. 

> As a side note it would be super cool if there was a way to somehow have a single github repo for demos vs needing to duplicate changes between this repo and plugin-tools

`create-plugin` templates are starting points which we try to keep fairly minimal so users don't have a ton to delete, but can still see "enough" to get started. We already get feedback that they are overly complex/cluttered. 

These examples can showcase more specific functionality or be fully featured demos. A potential enhancement we are considering is to allow create-plugin to eventually also load these as templates, for example `npx @grafana/create-plugin@latest --pluginType='scenesapp' --template='scenesapp-with-llm'`

I think this would make a great addition to the examples repository, but can I request we split this out into its own example called something like `app-with-scenes-llm` and there in the example readme indicate any particular requirements or caution over experimental APIs, i.e. https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-service-account. 

You could then remove other sections as you see fit compared to the current app-with-scenes example, to make this more focussed.

2024-04-28 21:10 UTC, nmarrs commented
> Hey @nmarrs thanks again for these contributions.
> 
> > As a side note it would be super cool if there was a way to somehow have a single github repo for demos vs needing to duplicate changes between this repo and plugin-tools
> 
> `create-plugin` templates are starting points which we try to keep fairly minimal so users don't have a ton to delete, but can still see "enough" to get started. We already get feedback that they are overly complex/cluttered.
> 
> These examples can showcase more specific functionality or be fully featured demos. A potential enhancement we are considering is to allow create-plugin to eventually also load these as templates, for example `npx @grafana/create-plugin@latest --pluginType='scenesapp' --template='scenesapp-with-llm'`
> 
> I think this would make a great addition to the examples repository, but can I request we split this out into its own example called something like `app-with-scenes-llm` and there in the example readme indicate any particular requirements or caution over experimental APIs, i.e. https://github.com/grafana/grafana-plugin-examples/tree/main/examples/app-with-service-account.
> 
> You could then remove other sections as you see fit compared to the current app-with-scenes example, to make this more focussed.

Hey @sympatheticmoose! I think this route sounds good - I will work on splitting out this example out and will re-request your review when it is ready to go. Re: `create-plugin` template I think it would be great to still try and include the basic LLM integration screen just for discoverability sake (see [this related comment](https://github.com/grafana/plugin-tools/pull/873#pullrequestreview-2005433239) on the related create plugin PR) but will defer to your judgement there 👍

2024-06-20 20:51 UTC, nmarrs commented
I've gone through and updated this to be a separate example. I'm having some troubles though testing this locally as when trying to open the app plugin it gets a bad request error. This should be ready though for re-review :) 

```
Error: Unknown Plugin
    at pluginSettings.ts:28:29
    at async As (AppRootPage.tsx:176:17)
```


https://github.com/grafana/grafana-plugin-examples/assets/22381771/67ba1ad4-e5f5-4838-a1e5-5e85b6cf735f

2025-05-08 12:24 UTC, academo commented
we are soon going to remove the scenes app example from the repository. closing this PR.

2025-05-08 12:24 UTC, closed without merging