Docs: Fix links broken by plugin-tools site reorg
grafana/grafana-plugin-examples pull request #343
Opened 2024-07-12 21:23 UTC by josmperez

2024-07-13 09:09 UTC, sympatheticmoose requested changes
A lot of these changes should be resolved by running `create-plugin update` which is done periodically. Given we have redirects in place I would prefer to wait until that has run then catch any remaining links rather than have to review 82 files 😅

2024-07-13 17:55 UTC, josmperez commented
> A lot of these changes should be resolved by running `create-plugin update` which is done periodically. Given we have redirects in place I would prefer to wait until that has run then catch any remaining links rather than have to review 82 files 😅

Sounds good. Let's wait a bit.

2024-07-15 07:55 UTC, academo commented
@josmperez 
I am curious to know if we didn't setup a redirect for https://grafana.com/developers/plugin-tools/create-a-plugin/extend-a-plugin/extend-configurations#extend-the-eslint-config

because many projects have these files with this links and people might follow them if they open those files and haven't run update (which is not very often)

2024-07-15 08:06 UTC, sympatheticmoose commented
@academo there's a redirect in the re-org PR https://github.com/grafana/plugin-tools/pull/993/files#diff-d8d70f81bb443af1e4aa5f4b0ce4ba1cc15800b67be29a2bcc66187fb3c10d5cR193-R194

2025-05-08 12:25 UTC, academo commented
I'll be closing this PR in an effort to clean up the repository.

2025-05-08 12:25 UTC, closed without merging